version: '3.8'
services:

  ora-db:
    image: "container-registry.oracle.com/database/express:latest"
    container_name: oradb 
    volumes:
      - option-battle-data:/opt/oracle/oradata
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD:12345

  backend:
    build: ./option-battle-app
    container_name: backend 
    environment:
      - DB_SERVER=ora-db
    ports:
      - 8080:8080
    links:
      - ora-db
    depends_on:
      - ora-db

  web:
    build: ./option-battle-web
    container_name: web
    ports:
      - 4200:80
    links:
      - backend


volumes:
  option-battle-data:
